// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: mt7987_spi

#ifndef _MT7987_SPI_UI_H
#define _MT7987_SPI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

// #include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_ethernet_png);    // assets/ethernet.png
LV_IMG_DECLARE(ui_img_cpu_png);    // assets/cpu.png
LV_IMG_DECLARE(ui_img_ram_png);    // assets/ram.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_calendar_png);    // assets/calendar.png
LV_IMG_DECLARE(ui_img_arrowdown_png);    // assets/arrowdown.png
LV_IMG_DECLARE(ui_img_arrowup_png);    // assets/arrowup.png
LV_IMG_DECLARE(ui_img_894798389);    // assets/hard-drive.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font2);
LV_FONT_DECLARE(ui_font_FontAmpm);
LV_FONT_DECLARE(ui_font_FontArcValue);
LV_FONT_DECLARE(ui_font_FontDate);
LV_FONT_DECLARE(ui_font_FontPi);
LV_FONT_DECLARE(ui_font_FontV4);
LV_FONT_DECLARE(ui_font_FontTime);
LV_FONT_DECLARE(ui_font_FontSecond);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
