// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: mt7987_spi

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_ImageBg2 = NULL;
lv_obj_t * ui_PanelTime = NULL;
lv_obj_t * ui_LabelAmpm = NULL;
lv_obj_t * ui_LabelHour = NULL;
lv_obj_t * ui_LabelColon = NULL;
lv_obj_t * ui_LabelMinute = NULL;
lv_obj_t * ui_LabelSecond = NULL;
lv_obj_t * ui_PanelDate = NULL;
lv_obj_t * ui_ImageDate = NULL;
lv_obj_t * ui_LabelDate = NULL;
lv_obj_t * ui_LabelWeek = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBg2 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_ImageBg2, &ui_img_bg2_png);
    lv_obj_set_width(ui_ImageBg2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBg2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBg2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBg2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBg2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelTime = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelTime, 428);
    lv_obj_set_height(ui_PanelTime, 100);
    lv_obj_set_x(ui_PanelTime, 0);
    lv_obj_set_y(ui_PanelTime, 21);
    lv_obj_set_align(ui_PanelTime, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTime, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTime, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTime, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelAmpm = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelAmpm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelAmpm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelAmpm, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LabelAmpm, "上午");
    lv_obj_set_style_text_font(ui_LabelAmpm, &ui_font_FontAmpm, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_LabelAmpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LabelAmpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LabelAmpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LabelAmpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHour = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHour, 58);
    lv_obj_set_y(ui_LabelHour, 0);
    lv_obj_set_align(ui_LabelHour, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LabelHour, "07");
    lv_obj_set_style_text_color(ui_LabelHour, lv_color_hex(0x00FF93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelHour, &ui_font_FontTime, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelColon = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelColon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelColon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelColon, -7);
    lv_obj_set_y(ui_LabelColon, 7);
    lv_obj_set_align(ui_LabelColon, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelColon, ":");
    lv_obj_set_style_text_color(ui_LabelColon, lv_color_hex(0x00FF93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelColon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelColon, &ui_font_FontTime, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinute = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMinute, 68);
    lv_obj_set_y(ui_LabelMinute, 0);
    lv_obj_set_align(ui_LabelMinute, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelMinute, "56");
    lv_obj_set_style_text_color(ui_LabelMinute, lv_color_hex(0x00FF93), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMinute, &ui_font_FontTime, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSecond = lv_label_create(ui_PanelTime);
    lv_obj_set_width(ui_LabelSecond, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSecond, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSecond, 3);
    lv_obj_set_y(ui_LabelSecond, -1);
    lv_obj_set_align(ui_LabelSecond, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LabelSecond, "30");
    lv_obj_set_style_text_font(ui_LabelSecond, &ui_font_FontSecond, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDate = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_PanelDate, 428);
    lv_obj_set_height(ui_PanelDate, 42);
    lv_obj_set_x(ui_PanelDate, 0);
    lv_obj_set_y(ui_PanelDate, -50);
    lv_obj_set_align(ui_PanelDate, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDate, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelDate, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelDate, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelDate, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageDate = lv_image_create(ui_PanelDate);
    lv_image_set_src(ui_ImageDate, &ui_img_calendar_png);
    lv_obj_set_width(ui_ImageDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageDate, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageDate, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelDate = lv_label_create(ui_PanelDate);
    lv_obj_set_width(ui_LabelDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDate, 0);
    lv_obj_set_y(ui_LabelDate, -1);
    lv_obj_set_align(ui_LabelDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate, "2026-02-27");
    lv_obj_set_style_text_font(ui_LabelDate, &ui_font_FontDate, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWeek = lv_label_create(ui_PanelDate);
    lv_obj_set_width(ui_LabelWeek, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWeek, 0);
    lv_obj_set_y(ui_LabelWeek, -2);
    lv_obj_set_align(ui_LabelWeek, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelWeek, "星期五");
    lv_obj_set_style_text_color(ui_LabelWeek, lv_color_hex(0xFF4900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWeek, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWeek, &ui_font_FontDate, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_ImageBg2 = NULL;
    ui_PanelTime = NULL;
    ui_LabelAmpm = NULL;
    ui_LabelHour = NULL;
    ui_LabelColon = NULL;
    ui_LabelMinute = NULL;
    ui_LabelSecond = NULL;
    ui_PanelDate = NULL;
    ui_ImageDate = NULL;
    ui_LabelDate = NULL;
    ui_LabelWeek = NULL;

}

void ui_Screen2_screen_relocalize(void)
{
    // label widgets on screen

}
