// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: mt7987_spi

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern void ui_Screen2_screen_relocalize(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_ImageBg2;
extern lv_obj_t * ui_PanelTime;
extern lv_obj_t * ui_LabelAmpm;
extern lv_obj_t * ui_LabelHour;
extern lv_obj_t * ui_LabelColon;
extern lv_obj_t * ui_LabelMinute;
extern lv_obj_t * ui_LabelSecond;
extern lv_obj_t * ui_PanelDate;
extern lv_obj_t * ui_ImageDate;
extern lv_obj_t * ui_LabelDate;
extern lv_obj_t * ui_LabelWeek;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

