// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: mt7987_spi

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ImageBg1 = NULL;
lv_obj_t * ui_PanelLan = NULL;
lv_obj_t * ui_PngWan = NULL;
lv_obj_t * ui_PanelLanValue = NULL;
lv_obj_t * ui_LabelLan = NULL;
lv_obj_t * ui_LabelLan6 = NULL;
lv_obj_t * ui_LabelEdgepi = NULL;
lv_obj_t * ui_LabelCustom = NULL;
lv_obj_t * ui_PanelDl = NULL;
lv_obj_t * ui_LabelDlSpeed = NULL;
lv_obj_t * ui_PanelUl = NULL;
lv_obj_t * ui_LabelUlSpeed = NULL;
lv_obj_t * ui_PanelCpu = NULL;
lv_obj_t * ui_PngCpu = NULL;
lv_obj_t * ui_LabelCpu = NULL;
lv_obj_t * ui_PanelRam = NULL;
lv_obj_t * ui_PngRam = NULL;
lv_obj_t * ui_LabelRam = NULL;
lv_obj_t * ui_PanelTemp = NULL;
lv_obj_t * ui_ImageTemp = NULL;
lv_obj_t * ui_LabelTemp = NULL;
lv_obj_t * ui_LabelFan = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBg1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageBg1, &ui_img_bg2_png);
    lv_obj_set_width(ui_ImageBg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBg1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelLan = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelLan, 428);
    lv_obj_set_height(ui_PanelLan, 68);
    lv_obj_set_x(ui_PanelLan, 0);
    lv_obj_set_y(ui_PanelLan, -37);
    lv_obj_set_align(ui_PanelLan, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelLan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLan, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelLan, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLan, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PngWan = lv_image_create(ui_PanelLan);
    lv_image_set_src(ui_PngWan, &ui_img_ethernet_png);
    lv_obj_set_width(ui_PngWan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PngWan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PngWan, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_PngWan, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PngWan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelLanValue = lv_obj_create(ui_PanelLan);
    lv_obj_set_width(ui_PanelLanValue, 240);
    lv_obj_set_height(ui_PanelLanValue, 68);
    lv_obj_set_x(ui_PanelLanValue, -81);
    lv_obj_set_y(ui_PanelLanValue, 0);
    lv_obj_set_align(ui_PanelLanValue, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelLanValue, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLanValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLanValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLanValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLanValue, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLanValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelLanValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLanValue, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLanValue, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLanValue, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLan = lv_label_create(ui_PanelLanValue);
    lv_obj_set_width(ui_LabelLan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLan, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelLan, "192.168.100.1");
    lv_obj_set_style_text_font(ui_LabelLan, &ui_font_FontV4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelLan6 = lv_label_create(ui_PanelLanValue);
    lv_obj_set_width(ui_LabelLan6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelLan6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelLan6, 4);
    lv_obj_set_y(ui_LabelLan6, 0);
    lv_obj_set_align(ui_LabelLan6, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LabelLan6, "fd96:0000:0000::1");
    lv_obj_set_style_text_font(ui_LabelLan6, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelEdgepi = lv_label_create(ui_PanelLan);
    lv_obj_set_width(ui_LabelEdgepi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelEdgepi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelEdgepi, 0);
    lv_obj_set_y(ui_LabelEdgepi, -2);
    lv_obj_set_align(ui_LabelEdgepi, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelEdgepi, "EdgePi");
    lv_obj_set_style_text_color(ui_LabelEdgepi, lv_color_hex(0xFF8C00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelEdgepi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelEdgepi, &ui_font_FontPi, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 自定义文本行（"EdgePi" 标识下方，可由 UCI custom_text 覆盖）
    ui_LabelCustom = lv_label_create(ui_PanelLan);
    lv_obj_set_width(ui_LabelCustom, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCustom, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCustom, LV_ALIGN_RIGHT_MID);
    lv_obj_set_y(ui_LabelCustom, 18);
    lv_label_set_text(ui_LabelCustom, "");
    lv_obj_set_style_text_color(ui_LabelCustom, lv_color_hex(0x00FFB6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelCustom, &ui_font_Font2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDl = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelDl, 214);
    lv_obj_set_height(ui_PanelDl, 36);
    lv_obj_set_x(ui_PanelDl, -107);
    lv_obj_set_y(ui_PanelDl, 15);
    lv_obj_set_align(ui_PanelDl, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelDl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelDl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelDl, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDlSpeed = lv_label_create(ui_PanelDl);
    lv_obj_set_width(ui_LabelDlSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDlSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDlSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDlSpeed, "下载: 100 B/s");
    lv_obj_set_style_text_color(ui_LabelDlSpeed, lv_color_hex(0x00FFB6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDlSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDlSpeed, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelUl = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelUl, 214);
    lv_obj_set_height(ui_PanelUl, 36);
    lv_obj_set_x(ui_PanelUl, 107);
    lv_obj_set_y(ui_PanelUl, 15);
    lv_obj_set_align(ui_PanelUl, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelUl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelUl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelUl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelUl, 4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUlSpeed = lv_label_create(ui_PanelUl);
    lv_obj_set_width(ui_LabelUlSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUlSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelUlSpeed, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUlSpeed, "上传: 26 B/s");
    lv_obj_set_style_text_color(ui_LabelUlSpeed, lv_color_hex(0x02A4FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUlSpeed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUlSpeed, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCpu = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelCpu, 142);
    lv_obj_set_height(ui_PanelCpu, 38);
    lv_obj_set_x(ui_PanelCpu, -143);
    lv_obj_set_y(ui_PanelCpu, 52);
    lv_obj_set_align(ui_PanelCpu, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelCpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelCpu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelCpu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelCpu, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelCpu, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelCpu, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PngCpu = lv_image_create(ui_PanelCpu);
    lv_image_set_src(ui_PngCpu, &ui_img_cpu_png);
    lv_obj_set_width(ui_PngCpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PngCpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PngCpu, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_PngCpu, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PngCpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelCpu = lv_label_create(ui_PanelCpu);
    lv_obj_set_width(ui_LabelCpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelCpu, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelCpu, "10 %");
    lv_obj_set_style_text_font(ui_LabelCpu, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRam = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelRam, 144);
    lv_obj_set_height(ui_PanelRam, 38);
    lv_obj_set_x(ui_PanelRam, 0);
    lv_obj_set_y(ui_PanelRam, 52);
    lv_obj_set_align(ui_PanelRam, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelRam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelRam, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelRam, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRam, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRam, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRam, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_PanelRam, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelRam, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_PngRam = lv_image_create(ui_PanelRam);
    lv_image_set_src(ui_PngRam, &ui_img_ram_png);
    lv_obj_set_width(ui_PngRam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PngRam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PngRam, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_PngRam, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_PngRam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelRam = lv_label_create(ui_PanelRam);
    lv_obj_set_width(ui_LabelRam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRam, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelRam, "36 %");
    lv_obj_set_style_text_font(ui_LabelRam, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTemp = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelTemp, 142);
    lv_obj_set_height(ui_PanelTemp, 38);
    lv_obj_set_x(ui_PanelTemp, 143);
    lv_obj_set_y(ui_PanelTemp, 52);
    lv_obj_set_align(ui_PanelTemp, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTemp, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTemp, 16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTemp, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageTemp = lv_image_create(ui_PanelTemp);
    lv_image_set_src(ui_ImageTemp, &ui_img_temperature_png);
    lv_obj_set_width(ui_ImageTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageTemp, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_ImageTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTemp = lv_label_create(ui_PanelTemp);
    lv_obj_set_width(ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTemp, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelTemp, "48 ℃");
    lv_obj_set_style_text_font(ui_LabelTemp, LV_FONT_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelFan = lv_label_create(ui_PanelTemp);
    lv_obj_set_width(ui_LabelFan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelFan, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LabelFan, "风扇 --");
    lv_obj_set_style_text_color(ui_LabelFan, lv_color_hex(0x00FFB6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFan, LV_FONT_DEFAULT, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ImageBg1 = NULL;
    ui_PanelLan = NULL;
    ui_PngWan = NULL;
    ui_PanelLanValue = NULL;
    ui_LabelLan = NULL;
    ui_LabelLan6 = NULL;
    ui_LabelEdgepi = NULL;
    ui_LabelCustom = NULL;
    ui_PanelDl = NULL;
    ui_LabelDlSpeed = NULL;
    ui_PanelUl = NULL;
    ui_LabelUlSpeed = NULL;
    ui_PanelCpu = NULL;
    ui_PngCpu = NULL;
    ui_LabelCpu = NULL;
    ui_PanelRam = NULL;
    ui_PngRam = NULL;
    ui_LabelRam = NULL;
    ui_PanelTemp = NULL;
    ui_ImageTemp = NULL;
    ui_LabelTemp = NULL;
    ui_LabelFan = NULL;

}

void ui_Screen1_screen_relocalize(void)
{
    // label widgets on screen

}
