// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: mt7987_spi

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_ImageBg4 = NULL;
lv_obj_t * ui_PanelArcCpu = NULL;
lv_obj_t * ui_PanelArcCpuKey = NULL;
lv_obj_t * ui_ImageArcCpu = NULL;
lv_obj_t * ui_LabelArcCpu = NULL;
lv_obj_t * ui_ArcCpu = NULL;
lv_obj_t * ui_LabelArcCpuValue = NULL;
lv_obj_t * ui_PanelArcRam = NULL;
lv_obj_t * ui_PanelArcRamKey = NULL;
lv_obj_t * ui_ImageArcRam = NULL;
lv_obj_t * ui_LabelArcRam = NULL;
lv_obj_t * ui_ArcRam = NULL;
lv_obj_t * ui_LabelArcRamValue = NULL;
lv_obj_t * ui_PanelArcTemp = NULL;
lv_obj_t * ui_PanelArcTempKey = NULL;
lv_obj_t * ui_ImageArcTemp = NULL;
lv_obj_t * ui_LabelArcTemp = NULL;
lv_obj_t * ui_ArcTemp = NULL;
lv_obj_t * ui_LabelArcTempValue = NULL;
lv_obj_t * ui_PanelArcDisk = NULL;
lv_obj_t * ui_PanelArcDiskKey = NULL;
lv_obj_t * ui_ImageArcDisk = NULL;
lv_obj_t * ui_LabelArcDisk = NULL;
lv_obj_t * ui_ArcDisk = NULL;
lv_obj_t * ui_LabelArcDiskValue = NULL;
// event funtions

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBg4 = lv_image_create(ui_Screen4);
    lv_image_set_src(ui_ImageBg4, &ui_img_bg2_png);
    lv_obj_set_width(ui_ImageBg4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBg4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBg4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBg4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBg4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelArcCpu = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelArcCpu, 107);
    lv_obj_set_height(ui_PanelArcCpu, 142);
    lv_obj_set_x(ui_PanelArcCpu, -161);
    lv_obj_set_y(ui_PanelArcCpu, 0);
    lv_obj_set_align(ui_PanelArcCpu, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelArcCpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelArcCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArcCpu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArcCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArcCpu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArcCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelArcCpu, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelArcCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelArcCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelArcCpu, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArcCpuKey = lv_obj_create(ui_PanelArcCpu);
    lv_obj_set_width(ui_PanelArcCpuKey, 97);
    lv_obj_set_height(ui_PanelArcCpuKey, 40);
    lv_obj_set_align(ui_PanelArcCpuKey, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_PanelArcCpuKey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelArcCpuKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArcCpuKey, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArcCpuKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArcCpuKey, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArcCpuKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelArcCpuKey, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelArcCpuKey, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelArcCpuKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelArcCpuKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageArcCpu = lv_image_create(ui_PanelArcCpuKey);
    lv_image_set_src(ui_ImageArcCpu, &ui_img_cpu_png);
    lv_obj_set_width(ui_ImageArcCpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArcCpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageArcCpu, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageArcCpu, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageArcCpu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelArcCpu = lv_label_create(ui_PanelArcCpuKey);
    lv_obj_set_width(ui_LabelArcCpu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcCpu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcCpu, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelArcCpu, "CPU");
    lv_obj_set_style_text_font(ui_LabelArcCpu, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcCpu = lv_arc_create(ui_PanelArcCpu);
    lv_obj_set_width(ui_ArcCpu, 90);
    lv_obj_set_height(ui_ArcCpu, 90);
    lv_obj_set_align(ui_ArcCpu, LV_ALIGN_BOTTOM_MID);
    lv_arc_set_value(ui_ArcCpu, 10);
    lv_arc_set_bg_angles(ui_ArcCpu, 90, 89);
    lv_obj_set_style_radius(ui_ArcCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ArcCpu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcCpu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_ArcCpu, lv_color_hex(0xC2C2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcCpu, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcCpu, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_ArcCpu, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcCpu, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcCpu, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelArcCpuValue = lv_label_create(ui_ArcCpu);
    lv_obj_set_width(ui_LabelArcCpuValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcCpuValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcCpuValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArcCpuValue, "10 %");
    lv_obj_set_style_text_font(ui_LabelArcCpuValue, &ui_font_FontArcValue, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArcRam = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelArcRam, 107);
    lv_obj_set_height(ui_PanelArcRam, 142);
    lv_obj_set_x(ui_PanelArcRam, -54);
    lv_obj_set_y(ui_PanelArcRam, 0);
    lv_obj_set_align(ui_PanelArcRam, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelArcRam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelArcRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArcRam, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArcRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArcRam, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArcRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelArcRam, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelArcRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelArcRam, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelArcRam, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArcRamKey = lv_obj_create(ui_PanelArcRam);
    lv_obj_set_width(ui_PanelArcRamKey, 97);
    lv_obj_set_height(ui_PanelArcRamKey, 40);
    lv_obj_set_align(ui_PanelArcRamKey, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_PanelArcRamKey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelArcRamKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArcRamKey, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArcRamKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArcRamKey, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArcRamKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelArcRamKey, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelArcRamKey, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelArcRamKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelArcRamKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageArcRam = lv_image_create(ui_PanelArcRamKey);
    lv_image_set_src(ui_ImageArcRam, &ui_img_ram_png);
    lv_obj_set_width(ui_ImageArcRam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArcRam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageArcRam, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageArcRam, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageArcRam, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelArcRam = lv_label_create(ui_PanelArcRamKey);
    lv_obj_set_width(ui_LabelArcRam, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcRam, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcRam, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelArcRam, "内存");
    lv_obj_set_style_text_font(ui_LabelArcRam, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcRam = lv_arc_create(ui_PanelArcRam);
    lv_obj_set_width(ui_ArcRam, 90);
    lv_obj_set_height(ui_ArcRam, 90);
    lv_obj_set_align(ui_ArcRam, LV_ALIGN_BOTTOM_MID);
    lv_arc_set_value(ui_ArcRam, 36);
    lv_arc_set_bg_angles(ui_ArcRam, 90, 89);
    lv_obj_set_style_arc_color(ui_ArcRam, lv_color_hex(0xC2C2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcRam, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcRam, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcRam, lv_color_hex(0x8BFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcRam, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcRam, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcRam, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcRam, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelArcRamValue = lv_label_create(ui_ArcRam);
    lv_obj_set_width(ui_LabelArcRamValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcRamValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcRamValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArcRamValue, "36 %");
    lv_obj_set_style_text_font(ui_LabelArcRamValue, &ui_font_FontArcValue, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArcTemp = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelArcTemp, 107);
    lv_obj_set_height(ui_PanelArcTemp, 142);
    lv_obj_set_x(ui_PanelArcTemp, 53);
    lv_obj_set_y(ui_PanelArcTemp, 0);
    lv_obj_set_align(ui_PanelArcTemp, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelArcTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelArcTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArcTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArcTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArcTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArcTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelArcTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelArcTemp, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelArcTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelArcTemp, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArcTempKey = lv_obj_create(ui_PanelArcTemp);
    lv_obj_set_width(ui_PanelArcTempKey, 97);
    lv_obj_set_height(ui_PanelArcTempKey, 40);
    lv_obj_set_align(ui_PanelArcTempKey, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_PanelArcTempKey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelArcTempKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArcTempKey, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArcTempKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArcTempKey, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArcTempKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelArcTempKey, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelArcTempKey, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelArcTempKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelArcTempKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageArcTemp = lv_image_create(ui_PanelArcTempKey);
    lv_image_set_src(ui_ImageArcTemp, &ui_img_temperature_png);
    lv_obj_set_width(ui_ImageArcTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArcTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageArcTemp, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageArcTemp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageArcTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelArcTemp = lv_label_create(ui_PanelArcTempKey);
    lv_obj_set_width(ui_LabelArcTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcTemp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelArcTemp, "温度");
    lv_obj_set_style_text_font(ui_LabelArcTemp, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp = lv_arc_create(ui_PanelArcTemp);
    lv_obj_set_width(ui_ArcTemp, 90);
    lv_obj_set_height(ui_ArcTemp, 90);
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_BOTTOM_MID);
    lv_arc_set_range(ui_ArcTemp, 0, 120);
    lv_arc_set_value(ui_ArcTemp, 50);
    lv_arc_set_bg_angles(ui_ArcTemp, 90, 89);
    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xC2C2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xFEC700), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTemp, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelArcTempValue = lv_label_create(ui_ArcTemp);
    lv_obj_set_width(ui_LabelArcTempValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcTempValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArcTempValue, "48 ℃");
    lv_obj_set_style_text_font(ui_LabelArcTempValue, &ui_font_FontArcValue, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArcDisk = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_PanelArcDisk, 107);
    lv_obj_set_height(ui_PanelArcDisk, 142);
    lv_obj_set_x(ui_PanelArcDisk, 160);
    lv_obj_set_y(ui_PanelArcDisk, 0);
    lv_obj_set_align(ui_PanelArcDisk, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelArcDisk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelArcDisk, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArcDisk, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArcDisk, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArcDisk, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArcDisk, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelArcDisk, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelArcDisk, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelArcDisk, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelArcDisk, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelArcDiskKey = lv_obj_create(ui_PanelArcDisk);
    lv_obj_set_width(ui_PanelArcDiskKey, 97);
    lv_obj_set_height(ui_PanelArcDiskKey, 40);
    lv_obj_set_align(ui_PanelArcDiskKey, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_PanelArcDiskKey, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelArcDiskKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelArcDiskKey, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelArcDiskKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelArcDiskKey, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelArcDiskKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelArcDiskKey, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelArcDiskKey, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelArcDiskKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelArcDiskKey, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageArcDisk = lv_image_create(ui_PanelArcDiskKey);
    lv_image_set_src(ui_ImageArcDisk, &ui_img_894798389);
    lv_obj_set_width(ui_ImageArcDisk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArcDisk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageArcDisk, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageArcDisk, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageArcDisk, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelArcDisk = lv_label_create(ui_PanelArcDiskKey);
    lv_obj_set_width(ui_LabelArcDisk, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcDisk, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcDisk, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelArcDisk, "磁盘");
    lv_obj_set_style_text_font(ui_LabelArcDisk, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcDisk = lv_arc_create(ui_PanelArcDisk);
    lv_obj_set_width(ui_ArcDisk, 90);
    lv_obj_set_height(ui_ArcDisk, 90);
    lv_obj_set_align(ui_ArcDisk, LV_ALIGN_BOTTOM_MID);
    lv_arc_set_value(ui_ArcDisk, 50);
    lv_arc_set_bg_angles(ui_ArcDisk, 90, 89);
    lv_obj_set_style_arc_color(ui_ArcDisk, lv_color_hex(0xC2C2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcDisk, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcDisk, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcDisk, lv_color_hex(0x00FFDD), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcDisk, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcDisk, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcDisk, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcDisk, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelArcDiskValue = lv_label_create(ui_ArcDisk);
    lv_obj_set_width(ui_LabelArcDiskValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelArcDiskValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelArcDiskValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelArcDiskValue, "8 %");
    lv_obj_set_style_text_font(ui_LabelArcDiskValue, &ui_font_FontArcValue, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_ImageBg4 = NULL;
    ui_PanelArcCpu = NULL;
    ui_PanelArcCpuKey = NULL;
    ui_ImageArcCpu = NULL;
    ui_LabelArcCpu = NULL;
    ui_ArcCpu = NULL;
    ui_LabelArcCpuValue = NULL;
    ui_PanelArcRam = NULL;
    ui_PanelArcRamKey = NULL;
    ui_ImageArcRam = NULL;
    ui_LabelArcRam = NULL;
    ui_ArcRam = NULL;
    ui_LabelArcRamValue = NULL;
    ui_PanelArcTemp = NULL;
    ui_PanelArcTempKey = NULL;
    ui_ImageArcTemp = NULL;
    ui_LabelArcTemp = NULL;
    ui_ArcTemp = NULL;
    ui_LabelArcTempValue = NULL;
    ui_PanelArcDisk = NULL;
    ui_PanelArcDiskKey = NULL;
    ui_ImageArcDisk = NULL;
    ui_LabelArcDisk = NULL;
    ui_ArcDisk = NULL;
    ui_LabelArcDiskValue = NULL;

}

void ui_Screen4_screen_relocalize(void)
{
    // label widgets on screen

}
