// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: mt7987_spi

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_ImageBg3 = NULL;
lv_obj_t * ui_PanelChartDl = NULL;
lv_obj_t * ui_ChartDlSpeed = NULL;
lv_obj_t * ui_ChartDlSpeed_Xaxis = NULL;
lv_obj_t * ui_ChartDlSpeed_Yaxis1 = NULL;
lv_obj_t * ui_ChartDlSpeed_Yaxis2 = NULL;
lv_obj_t * ui_PanelLabelDl1 = NULL;
lv_obj_t * ui_ImageArrowDown = NULL;
lv_obj_t * ui_LabelChartDlKey = NULL;
lv_obj_t * ui_PanelLabelDl2 = NULL;
lv_obj_t * ui_LabelChartDlValue = NULL;
lv_obj_t * ui_PanelChartUl = NULL;
lv_obj_t * ui_ChartUlSpeed = NULL;
lv_obj_t * ui_ChartUlSpeed_Xaxis = NULL;
lv_obj_t * ui_ChartUlSpeed_Yaxis1 = NULL;
lv_obj_t * ui_ChartUlSpeed_Yaxis2 = NULL;
lv_obj_t * ui_PanelLabelUl1 = NULL;
lv_obj_t * ui_ImageArrowUp = NULL;
lv_obj_t * ui_LabelChartUlSpeed = NULL;
lv_obj_t * ui_PanelLabelUl2 = NULL;
lv_obj_t * ui_LabelChartUlValue = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageBg3 = lv_image_create(ui_Screen3);
    lv_image_set_src(ui_ImageBg3, &ui_img_bg2_png);
    lv_obj_set_width(ui_ImageBg3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageBg3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageBg3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageBg3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageBg3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelChartDl = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelChartDl, 428);
    lv_obj_set_height(ui_PanelChartDl, 71);
    lv_obj_set_x(ui_PanelChartDl, 0);
    lv_obj_set_y(ui_PanelChartDl, -36);
    lv_obj_set_align(ui_PanelChartDl, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelChartDl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartDl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelChartDl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelChartDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelChartDl, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelChartDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelChartDl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelChartDl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartDlSpeed = lv_chart_create(ui_PanelChartDl);
    lv_obj_set_width(ui_ChartDlSpeed, 288);
    lv_obj_set_height(ui_ChartDlSpeed, 60);
    lv_obj_set_x(ui_ChartDlSpeed, 0);
    lv_obj_set_y(ui_ChartDlSpeed, 1);
    lv_obj_set_align(ui_ChartDlSpeed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ChartDlSpeed, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_ChartDlSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_ChartDlSpeed,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_ChartDlSpeed, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_ChartDlSpeed, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_ChartDlSpeed, 60);
    lv_chart_set_div_line_count(ui_ChartDlSpeed, 0, 0);
    lv_obj_set_style_radius(ui_ChartDlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartDlSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartDlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartDlSpeed, lv_color_hex(0xF5DF09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartDlSpeed, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_ChartDlSpeed, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_ChartDlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ChartDlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ChartDlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ChartDlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ChartDlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ChartDlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ChartDlSpeed, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartDlSpeed_Xaxis = lv_scale_create(ui_ChartDlSpeed);
    lv_scale_set_mode(ui_ChartDlSpeed_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_ChartDlSpeed_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_ChartDlSpeed_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_ChartDlSpeed_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_ChartDlSpeed,
                                                                         LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartDlSpeed, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_ChartDlSpeed_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartDlSpeed_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_ChartDlSpeed_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartDlSpeed_Xaxis, 6, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_ChartDlSpeed_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_ChartDlSpeed_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_ChartDlSpeed_Xaxis, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ChartDlSpeed_Xaxis, 2 >= 1 ? 2 : 1);
    ui_ChartDlSpeed_Yaxis1 = lv_scale_create(ui_ChartDlSpeed);
    lv_scale_set_mode(ui_ChartDlSpeed_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_ChartDlSpeed_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_ChartDlSpeed_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_ChartDlSpeed_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_ChartDlSpeed,
                                                                         LV_PART_MAIN) - lv_obj_get_style_border_width(ui_ChartDlSpeed, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_ChartDlSpeed_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartDlSpeed_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartDlSpeed_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartDlSpeed_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartDlSpeed_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_ChartDlSpeed_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ChartDlSpeed_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_ChartDlSpeed_Yaxis2 = lv_scale_create(ui_ChartDlSpeed);
    lv_scale_set_mode(ui_ChartDlSpeed_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_ChartDlSpeed_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_ChartDlSpeed_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_ChartDlSpeed_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_ChartDlSpeed,
                                                                         LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartDlSpeed, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_ChartDlSpeed_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartDlSpeed_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartDlSpeed_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartDlSpeed_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartDlSpeed_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_ChartDlSpeed_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ChartDlSpeed_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_chart_series_t * ui_ChartDlSpeed_series_1 = lv_chart_add_series(ui_ChartDlSpeed, lv_color_hex(0x00FFB6),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartDlSpeed_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0, 8, 2, 4, 7, 0 };
    lv_chart_set_series_ext_y_array(ui_ChartDlSpeed, ui_ChartDlSpeed_series_1, ui_ChartDlSpeed_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_ChartDlSpeed, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_ChartDlSpeed, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_PanelLabelDl1 = lv_obj_create(ui_PanelChartDl);
    lv_obj_set_width(ui_PanelLabelDl1, 126);
    lv_obj_set_height(ui_PanelLabelDl1, 40);
    lv_obj_set_x(ui_PanelLabelDl1, 145);
    lv_obj_set_y(ui_PanelLabelDl1, -16);
    lv_obj_set_align(ui_PanelLabelDl1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelLabelDl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLabelDl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLabelDl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLabelDl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLabelDl1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLabelDl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelLabelDl1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLabelDl1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLabelDl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLabelDl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageArrowDown = lv_image_create(ui_PanelLabelDl1);
    lv_image_set_src(ui_ImageArrowDown, &ui_img_arrowdown_png);
    lv_obj_set_width(ui_ImageArrowDown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArrowDown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageArrowDown, 0);
    lv_obj_set_y(ui_ImageArrowDown, 2);
    lv_obj_set_align(ui_ImageArrowDown, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageArrowDown, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageArrowDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelChartDlKey = lv_label_create(ui_PanelLabelDl1);
    lv_obj_set_width(ui_LabelChartDlKey, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChartDlKey, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChartDlKey, 0);
    lv_obj_set_y(ui_LabelChartDlKey, 2);
    lv_obj_set_align(ui_LabelChartDlKey, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelChartDlKey, "下载");
    lv_obj_set_style_text_font(ui_LabelChartDlKey, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLabelDl2 = lv_obj_create(ui_PanelChartDl);
    lv_obj_set_width(ui_PanelLabelDl2, 126);
    lv_obj_set_height(ui_PanelLabelDl2, 31);
    lv_obj_set_x(ui_PanelLabelDl2, 145);
    lv_obj_set_y(ui_PanelLabelDl2, 19);
    lv_obj_set_align(ui_PanelLabelDl2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelLabelDl2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLabelDl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLabelDl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLabelDl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLabelDl2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLabelDl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_pad_left(ui_PanelLabelDl2, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLabelDl2, 12, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLabelDl2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLabelDl2, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_LabelChartDlValue = lv_label_create(ui_PanelLabelDl2);
    lv_obj_set_width(ui_LabelChartDlValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChartDlValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelChartDlValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChartDlValue, "100 MB/s");
    lv_obj_set_style_text_color(ui_LabelChartDlValue, lv_color_hex(0x00FFB6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChartDlValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChartDlValue, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelChartUl = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_PanelChartUl, 428);
    lv_obj_set_height(ui_PanelChartUl, 71);
    lv_obj_set_x(ui_PanelChartUl, 0);
    lv_obj_set_y(ui_PanelChartUl, 35);
    lv_obj_set_align(ui_PanelChartUl, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelChartUl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelChartUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelChartUl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelChartUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelChartUl, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelChartUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelChartUl, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelChartUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelChartUl, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelChartUl, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartUlSpeed = lv_chart_create(ui_PanelChartUl);
    lv_obj_set_width(ui_ChartUlSpeed, 288);
    lv_obj_set_height(ui_ChartUlSpeed, 60);
    lv_obj_set_x(ui_ChartUlSpeed, 0);
    lv_obj_set_y(ui_ChartUlSpeed, -1);
    lv_obj_set_align(ui_ChartUlSpeed, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ChartUlSpeed, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_ChartUlSpeed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_ChartUlSpeed,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_ChartUlSpeed, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_ChartUlSpeed, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_ChartUlSpeed, 60);
    lv_chart_set_div_line_count(ui_ChartUlSpeed, 0, 0);
    lv_obj_set_style_radius(ui_ChartUlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ChartUlSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ChartUlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ChartUlSpeed, lv_color_hex(0xF5DF09), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ChartUlSpeed, 160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ChartUlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ChartUlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ChartUlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ChartUlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ChartUlSpeed, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ChartUlSpeed, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChartUlSpeed_Xaxis = lv_scale_create(ui_ChartUlSpeed);
    lv_scale_set_mode(ui_ChartUlSpeed_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_ChartUlSpeed_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_ChartUlSpeed_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_ChartUlSpeed_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_ChartUlSpeed,
                                                                         LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartUlSpeed, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_ChartUlSpeed_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartUlSpeed_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_ChartUlSpeed_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartUlSpeed_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_ChartUlSpeed_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_ChartUlSpeed_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_ChartUlSpeed_Xaxis, (5 > 0 ? 5 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_ChartUlSpeed_Xaxis, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_ChartUlSpeed_Xaxis, false);
    ui_ChartUlSpeed_Yaxis1 = lv_scale_create(ui_ChartUlSpeed);
    lv_scale_set_mode(ui_ChartUlSpeed_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_ChartUlSpeed_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_ChartUlSpeed_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_ChartUlSpeed_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_ChartUlSpeed,
                                                                         LV_PART_MAIN) - lv_obj_get_style_border_width(ui_ChartUlSpeed, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_ChartUlSpeed_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartUlSpeed_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartUlSpeed_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartUlSpeed_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartUlSpeed_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_ChartUlSpeed_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ChartUlSpeed_Yaxis1, 2 >= 1 ? 2 : 1);
    ui_ChartUlSpeed_Yaxis2 = lv_scale_create(ui_ChartUlSpeed);
    lv_scale_set_mode(ui_ChartUlSpeed_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_ChartUlSpeed_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_ChartUlSpeed_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_ChartUlSpeed_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_ChartUlSpeed,
                                                                         LV_PART_MAIN) + lv_obj_get_style_border_width(ui_ChartUlSpeed, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_ChartUlSpeed_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_ChartUlSpeed_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_ChartUlSpeed_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_ChartUlSpeed_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_ChartUlSpeed_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_ChartUlSpeed_Yaxis2, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_ChartUlSpeed_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_ChartUlSpeed_Yaxis2, false);
    lv_chart_series_t * ui_ChartUlSpeed_series_1 = lv_chart_add_series(ui_ChartUlSpeed, lv_color_hex(0x02A4FD),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartUlSpeed_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_series_ext_y_array(ui_ChartUlSpeed, ui_ChartUlSpeed_series_1, ui_ChartUlSpeed_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_ChartUlSpeed, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_ChartUlSpeed, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_PanelLabelUl1 = lv_obj_create(ui_PanelChartUl);
    lv_obj_set_width(ui_PanelLabelUl1, 126);
    lv_obj_set_height(ui_PanelLabelUl1, 40);
    lv_obj_set_x(ui_PanelLabelUl1, 145);
    lv_obj_set_y(ui_PanelLabelUl1, -14);
    lv_obj_set_align(ui_PanelLabelUl1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelLabelUl1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLabelUl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLabelUl1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLabelUl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLabelUl1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLabelUl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelLabelUl1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelLabelUl1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelLabelUl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelLabelUl1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageArrowUp = lv_image_create(ui_PanelLabelUl1);
    lv_image_set_src(ui_ImageArrowUp, &ui_img_arrowup_png);
    lv_obj_set_width(ui_ImageArrowUp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageArrowUp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageArrowUp, 0);
    lv_obj_set_y(ui_ImageArrowUp, 2);
    lv_obj_set_align(ui_ImageArrowUp, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_ImageArrowUp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageArrowUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelChartUlSpeed = lv_label_create(ui_PanelLabelUl1);
    lv_obj_set_width(ui_LabelChartUlSpeed, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChartUlSpeed, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelChartUlSpeed, 0);
    lv_obj_set_y(ui_LabelChartUlSpeed, 2);
    lv_obj_set_align(ui_LabelChartUlSpeed, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelChartUlSpeed, "上传");
    lv_obj_set_style_text_font(ui_LabelChartUlSpeed, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelLabelUl2 = lv_obj_create(ui_PanelChartUl);
    lv_obj_set_width(ui_PanelLabelUl2, 126);
    lv_obj_set_height(ui_PanelLabelUl2, 31);
    lv_obj_set_x(ui_PanelLabelUl2, 145);
    lv_obj_set_y(ui_PanelLabelUl2, 21);
    lv_obj_set_align(ui_PanelLabelUl2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PanelLabelUl2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelLabelUl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelLabelUl2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelLabelUl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelLabelUl2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelLabelUl2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelChartUlValue = lv_label_create(ui_PanelLabelUl2);
    lv_obj_set_width(ui_LabelChartUlValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelChartUlValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelChartUlValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelChartUlValue, "210 KB/s");
    lv_obj_set_style_text_color(ui_LabelChartUlValue, lv_color_hex(0x02A4FD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelChartUlValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelChartUlValue, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_ImageBg3 = NULL;
    ui_PanelChartDl = NULL;
    ui_ChartDlSpeed = NULL;
    ui_PanelLabelDl1 = NULL;
    ui_ImageArrowDown = NULL;
    ui_LabelChartDlKey = NULL;
    ui_PanelLabelDl2 = NULL;
    ui_LabelChartDlValue = NULL;
    ui_PanelChartUl = NULL;
    ui_ChartUlSpeed = NULL;
    ui_PanelLabelUl1 = NULL;
    ui_ImageArrowUp = NULL;
    ui_LabelChartUlSpeed = NULL;
    ui_PanelLabelUl2 = NULL;
    ui_LabelChartUlValue = NULL;

}

void ui_Screen3_screen_relocalize(void)
{
    // label widgets on screen

}
