// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: mt7987_spi

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern void ui_Screen1_screen_relocalize(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ImageBg1;
extern lv_obj_t * ui_PanelLan;
extern lv_obj_t * ui_PngWan;
extern lv_obj_t * ui_PanelLanValue;
extern lv_obj_t * ui_LabelLan;
extern lv_obj_t * ui_LabelLan6;
extern lv_obj_t * ui_LabelEdgepi;
extern lv_obj_t * ui_LabelCustom;
extern lv_obj_t * ui_PanelDl;
extern lv_obj_t * ui_LabelDlSpeed;
extern lv_obj_t * ui_PanelUl;
extern lv_obj_t * ui_LabelUlSpeed;
extern lv_obj_t * ui_PanelCpu;
extern lv_obj_t * ui_PngCpu;
extern lv_obj_t * ui_LabelCpu;
extern lv_obj_t * ui_PanelRam;
extern lv_obj_t * ui_PngRam;
extern lv_obj_t * ui_LabelRam;
extern lv_obj_t * ui_PanelTemp;
extern lv_obj_t * ui_ImageTemp;
extern lv_obj_t * ui_LabelTemp;
extern lv_obj_t * ui_LabelFan;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

