// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: mt7987_spi

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern void ui_Screen4_screen_relocalize(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_ImageBg4;
extern lv_obj_t * ui_PanelArcCpu;
extern lv_obj_t * ui_PanelArcCpuKey;
extern lv_obj_t * ui_ImageArcCpu;
extern lv_obj_t * ui_LabelArcCpu;
extern lv_obj_t * ui_ArcCpu;
extern lv_obj_t * ui_LabelArcCpuValue;
extern lv_obj_t * ui_PanelArcRam;
extern lv_obj_t * ui_PanelArcRamKey;
extern lv_obj_t * ui_ImageArcRam;
extern lv_obj_t * ui_LabelArcRam;
extern lv_obj_t * ui_ArcRam;
extern lv_obj_t * ui_LabelArcRamValue;
extern lv_obj_t * ui_PanelArcTemp;
extern lv_obj_t * ui_PanelArcTempKey;
extern lv_obj_t * ui_ImageArcTemp;
extern lv_obj_t * ui_LabelArcTemp;
extern lv_obj_t * ui_ArcTemp;
extern lv_obj_t * ui_LabelArcTempValue;
extern lv_obj_t * ui_PanelArcDisk;
extern lv_obj_t * ui_PanelArcDiskKey;
extern lv_obj_t * ui_ImageArcDisk;
extern lv_obj_t * ui_LabelArcDisk;
extern lv_obj_t * ui_ArcDisk;
extern lv_obj_t * ui_LabelArcDiskValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

