// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: mt7987_spi

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern void ui_Screen3_screen_relocalize(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_ImageBg3;
extern lv_obj_t * ui_PanelChartDl;
extern lv_obj_t * ui_ChartDlSpeed;
extern lv_obj_t * ui_ChartDlSpeed_Xaxis;
extern lv_obj_t * ui_ChartDlSpeed_Yaxis1;
extern lv_obj_t * ui_ChartDlSpeed_Yaxis2;
extern lv_obj_t * ui_PanelLabelDl1;
extern lv_obj_t * ui_ImageArrowDown;
extern lv_obj_t * ui_LabelChartDlKey;
extern lv_obj_t * ui_PanelLabelDl2;
extern lv_obj_t * ui_LabelChartDlValue;
extern lv_obj_t * ui_PanelChartUl;
extern lv_obj_t * ui_ChartUlSpeed;
extern lv_obj_t * ui_ChartUlSpeed_Xaxis;
extern lv_obj_t * ui_ChartUlSpeed_Yaxis1;
extern lv_obj_t * ui_ChartUlSpeed_Yaxis2;
extern lv_obj_t * ui_PanelLabelUl1;
extern lv_obj_t * ui_ImageArrowUp;
extern lv_obj_t * ui_LabelChartUlSpeed;
extern lv_obj_t * ui_PanelLabelUl2;
extern lv_obj_t * ui_LabelChartUlValue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

